name: artifact_demo

on: push

jobs:
  upload_artifact:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: "create loacal file"
        run: echo "creating a file and uploading to workflow and donwload from there" > file.txt

      - uses: actions/upload-artifact@v2
        with: 
          name: file
          path: file.txt
          retention-days: 10

  download_artifact:
    name: download artifact
    runs-on: ubuntu-latest
    needs: upload_artifact
    steps:
      - name: file
        run: echo "downloading file"

      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
