name: github_environment

on: 
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: prod
      url: http://hithub.com
    
    steps:
      - name: 'printing from env varialbles' 
        run: |
          echo "my_sercret: ${{ secrets.PROD_SECRET }}" 